export {default as Card} from "./card/card";
export {default as Nav} from "./nav/nav";
export {default as Account} from "./account/account";
export {default as Banner} from "./banner/banner";
export {default as Comment} from "./post/comment/comment";
export {default as Comments} from "./post/comments/comments";
export {default as MyGames} from "./mygames/mygames";
export {default as Friend} from "./friends/friends";
export {default as GameWeek} from "./gameweek/gameweek";
export {default as Notification} from "./notification/notification";
export {default as Profile} from "./profile/profile";
export {default as Search} from "./search/search";
export {default as Settings} from "./settings/settings";
export {default as Bar} from "./search/bar/bar";
export {default as Post} from "./post/post";
export {default as User} from "./post/user/user";
export {default as UserInfo} from "./profile/UserInfo/userInfo"
export {default as RecentlyGames} from "./profile/gamesRecently/gamesRecently"
export {default as ContenProfile} from "./profile/content/content"
export {default as Form} from "./form/form"
export {default as LoginMobile} from "./login_(mobile)/login"
export {default as RecentlyPlay} from "./mygames/recentlyplayed/recentlyplayed";
export {default as Games} from "./mygames/games/games";
export {default as SearchGames} from "./searchgames/searchgames";
export {default as RecentlyAddd} from "./profile/gamesRecently/recentlyadd/recentlyeadd";
export {default as Linked} from "./settings/linked/linked";
export {default as Link} from "./settings/linkto/link";
export {default as Status} from "./settings/status/status";
export {default as LogOut} from "./settings/btnLogout/logout";
export {default as Inputs} from "./account/inputs/inputs";
export {default as Favorites} from "./favorites/favorites";
export {default as Social} from "./social/social";
