export { default as Card } from "./card/card";
export { default as Nav } from "./nav/nav";
export { default as Account } from "./account/account";
export { default as Banner } from "./banner/banner";
export { default as Comment } from "./post/comment/comment";
export { default as Comments } from "./post/comments/comments";
export { default as MyGames } from "./mygames/mygames";
export { default as Friend } from "./friends/friends";
export { default as GameWeek } from "./GameWeek/gameWeek";
export { default as Notification } from "./notification/notification";
export { default as Search } from "./search/search";
export { default as Settings } from "./settings/settings";
export { default as Bar } from "./search/bar/bar";
export { default as Post } from "./post/post";
export { default as User } from "./post/user/user";
export { default as UserInfo } from "./profile/UserInfo/userInfo"
export { default as RecentlyGames } from "./profile/gamesRecently/gamesRecently"
export { default as Form } from "./form/form"
export { default as FormR } from "./form/formR"
export { default as LoginMobile } from "./login_(mobile)/login"
export { default as RecentlyPlay } from "./mygames/recentlyplayed/recentlyplayed";
export { default as Games } from "./mygames/games/games";
export { default as SearchGames } from "./searchgames/searchgames";
export { default as RecentlyAddd } from "./profile/gamesRecently/recentlyadd/recentlyeadd";
export { default as Linked } from "./settings/linked/linked";
export { default as Link } from "./settings/linkto/link";
export { default as Status } from "./settings/status/status";
export { default as LogOut } from "./settings/btnLogout/logout";
export { default as Inputs } from "./account/inputs/inputs";
export { default as Favorites } from "./favorites/favorites";
export { default as Social } from "./social/social";
export { default as ProfileFavorites } from "./profile/profile_favorites/profile"
export { default as ProfileFriends } from "./profile/profile_friends/profile"
export { default as ProfileNotification } from "./profile/profile_notification/profile"
export { default as ProfileSettings } from "./profile/profile_notification/profile"
export { default as ProfileAccount } from "./profile/profile_account/profile"
export { default as ContenProfileAccount } from "./profile/profile_account/content_account/content"
export { default as ContenProfileFavorites } from "./profile/profile_favorites/content_favorites/content"
export { default as ContenProfileFriends } from "./profile/profile_friends/content_friends/content"
export { default as ContenProfileSettings } from "./profile/profile_settings/content_settings/content"
export { default as ContenProfileNotification } from "./profile/profile_notification/content_notifcation/content"