export { default as Dashboard } from "./Dashboard/dashboard";
export { default as Login } from "./Login/login";
export { default as Register } from "./Register/register";
export { default as Home } from "./Home/home";
export { default as Post } from "./Post/post";
export { default as Mygames } from "./Mygames/mygames";
export { default as Accounts } from "./Account/account"
export { default as ProfilesAccount } from "./Profile_account/profile";
export { default as ProfilesFavorites } from "./Profile_favorites//profile";
export { default as ProfilesFriends } from "./Profile_friends/profile";
export { default as Profilesnotification } from "./Profile_notification/profile";
export { default as ProfilesSettings } from "./Profile_settings/profile";